name: sendbird_uikit
description: With Sendbird UIKit for Flutter, you can easily build an in-app chat with all the essential messaging features.
version: 1.2.0
homepage: https://sendbird.com
repository: https://github.com/sendbird/sendbird-uikit-flutter
documentation: https://sendbird.com/docs/chat/uikit/v3/flutter/overview

environment:
  sdk: '>=3.3.0 <4.0.0'

platforms:
  android:
  ios:
  web:

dependencies:
  flutter:
    sdk: flutter

  sendbird_chat_sdk: ^4.7.0
  provider: ^6.1.2
  intl: '>=0.18.1 <1.0.0'
  collection: ^1.18.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.5
  http: ^1.2.1
  web_socket_channel: 2.4.0
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.3
  gif: ^2.3.0
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansKR-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansKR-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansKR-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansKR-Black.ttf
          weight: 900
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
    - family: SendbirdIcons
      fonts:
        - asset: packages/sendbird_uikit/fonts/SendbirdIcons.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
